name: expense_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  firebase_app_check: ^0.3.1+6
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  path: ^1.9.0
  google_sign_in: ^6.2.2
  connectivity_plus: ^6.1.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7
  timezone: ^0.10.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  syncfusion_flutter_charts: ^27.2.5
  dropdown_button2: ^2.3.9
  pin_code_fields: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  onboarding: ^4.0.2
  introduction_screen: ^3.1.14
  date_picker_plus: ^4.1.0
  buttons_tabbar: ^1.3.14
  flutter_svg: ^2.0.16
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.3.3
  unorm_dart: ^0.3.0
  get_storage: ^2.1.1
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
